package com.umb.cs682.projectlupus.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.umb.cs682.projectlupus.domain.Medicine;
import com.umb.cs682.projectlupus.db.helpers.DaoSession;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MEDICINE.
*/
public class MedicineDao extends AbstractDao<Medicine, Long> {

    public static final String TABLENAME = "MEDICINE";

    /**
     * Properties of entity Medicine.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MedName = new Property(1, String.class, "medName", false, "MED_NAME");
        public final static Property Dosage = new Property(2, int.class, "dosage", false, "DOSAGE");
        public final static Property Units = new Property(3, String.class, "units", false, "UNITS");
        public final static Property Notes = new Property(4, String.class, "notes", false, "NOTES");
    };

    private DaoSession daoSession;


    public MedicineDao(DaoConfig config) {
        super(config);
    }
    
    public MedicineDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MEDICINE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'MED_NAME' TEXT NOT NULL ," + // 1: medName
                "'DOSAGE' INTEGER NOT NULL ," + // 2: dosage
                "'UNITS' TEXT NOT NULL ," + // 3: units
                "'NOTES' TEXT);"); // 4: notes
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MEDICINE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Medicine entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getMedName());
        stmt.bindLong(3, entity.getDosage());
        stmt.bindString(4, entity.getUnits());
 
        String notes = entity.getNotes();
        if (notes != null) {
            stmt.bindString(5, notes);
        }
    }

    @Override
    protected void attachEntity(Medicine entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Medicine readEntity(Cursor cursor, int offset) {
        Medicine entity = new Medicine( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // medName
            cursor.getInt(offset + 2), // dosage
            cursor.getString(offset + 3), // units
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // notes
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Medicine entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMedName(cursor.getString(offset + 1));
        entity.setDosage(cursor.getInt(offset + 2));
        entity.setUnits(cursor.getString(offset + 3));
        entity.setNotes(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Medicine entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Medicine entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
