package com.umb.cs682.projectlupus.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ACTIVITY_SENSE.
 */
public class ActivitySense {

    private Long id;
    private int stepCount;
    /** Not-null value. */
    private java.util.Date date;

    public ActivitySense() {
    }

    public ActivitySense(Long id) {
        this.id = id;
    }

    public ActivitySense(Long id, int stepCount, java.util.Date date) {
        this.id = id;
        this.stepCount = stepCount;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getStepCount() {
        return stepCount;
    }

    public void setStepCount(int stepCount) {
        this.stepCount = stepCount;
    }

    /** Not-null value. */
    public java.util.Date getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
