package com.umb.cs682.projectlupus.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MEDICINE_INTAKE.
 */
public class MedicineIntakeBO {

    private Long id;
    private long reminderId;
    private Integer remindedCount;
    private Integer intakeCount;

    public MedicineIntakeBO() {
    }

    public MedicineIntakeBO(Long id) {
        this.id = id;
    }

    public MedicineIntakeBO(Long id, long reminderId, Integer remindedCount, Integer intakeCount) {
        this.id = id;
        this.reminderId = reminderId;
        this.remindedCount = remindedCount;
        this.intakeCount = intakeCount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getReminderId() {
        return reminderId;
    }

    public void setReminderId(long reminderId) {
        this.reminderId = reminderId;
    }

    public Integer getRemindedCount() {
        return remindedCount;
    }

    public void setRemindedCount(Integer remindedCount) {
        this.remindedCount = remindedCount;
    }

    public Integer getIntakeCount() {
        return intakeCount;
    }

    public void setIntakeCount(Integer intakeCount) {
        this.intakeCount = intakeCount;
    }

}
