package com.umb.cs682.projectlupus.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MOOD_LEVEL.
 */
public class MoodLevel {

    private Long id;
    private long reminderId;
    /** Not-null value. */
    private java.util.Date date;
    private int moodLevel;

    public MoodLevel() {
    }

    public MoodLevel(Long id) {
        this.id = id;
    }

    public MoodLevel(Long id, long reminderId, java.util.Date date, int moodLevel) {
        this.id = id;
        this.reminderId = reminderId;
        this.date = date;
        this.moodLevel = moodLevel;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getReminderId() {
        return reminderId;
    }

    public void setReminderId(long reminderId) {
        this.reminderId = reminderId;
    }

    /** Not-null value. */
    public java.util.Date getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public int getMoodLevel() {
        return moodLevel;
    }

    public void setMoodLevel(int moodLevel) {
        this.moodLevel = moodLevel;
    }

}
